/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as OrderRouteRouteImport } from './app/routes/_order/route'
import { Route as OrderLayoutRouteRouteImport } from './app/routes/_order/_layout/route'
import { Route as OrderLayoutIndexRouteImport } from './app/routes/_order/_layout/index'
import { Route as OrderLayoutNotFoundRouteImport } from './app/routes/_order/_layout/$notFound'
import { Route as OrderLayoutSuccessIndexRouteImport } from './app/routes/_order/_layout/success/index'
import { Route as OrderLayoutCompanyLocation_idUser_idRouteRouteImport } from './app/routes/_order/_layout/$company/$location_id/$user_id/route'
import { Route as OrderLayoutCompanyLocation_idUser_idIndexRouteImport } from './app/routes/_order/_layout/$company/$location_id/$user_id/index'
import { Route as OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRouteImport } from './app/routes/_order/_layout/$company/$location_id/$user_id/$service_id/confirm/index'
import { Route as OrderLayoutCompanyLocation_idUser_idService_idDateIndexRouteImport } from './app/routes/_order/_layout/$company/$location_id/$user_id/$service_id/date/index'

const OrderRouteRoute = OrderRouteRouteImport.update({
  id: '/_order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderLayoutRouteRoute = OrderLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OrderRouteRoute,
} as any)
const OrderLayoutIndexRoute = OrderLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrderLayoutRouteRoute,
} as any)
const OrderLayoutNotFoundRoute = OrderLayoutNotFoundRouteImport.update({
  id: '/$notFound',
  path: '/$notFound',
  getParentRoute: () => OrderLayoutRouteRoute,
} as any)
const OrderLayoutSuccessIndexRoute = OrderLayoutSuccessIndexRouteImport.update({
  id: '/success/',
  path: '/success/',
  getParentRoute: () => OrderLayoutRouteRoute,
} as any)
const OrderLayoutCompanyLocation_idUser_idRouteRoute =
  OrderLayoutCompanyLocation_idUser_idRouteRouteImport.update({
    id: '/$company/$location_id/$user_id',
    path: '/$company/$location_id/$user_id',
    getParentRoute: () => OrderLayoutRouteRoute,
  } as any)
const OrderLayoutCompanyLocation_idUser_idIndexRoute =
  OrderLayoutCompanyLocation_idUser_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrderLayoutCompanyLocation_idUser_idRouteRoute,
  } as any)
const OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute =
  OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRouteImport.update({
    id: '/$service_id/confirm/',
    path: '/$service_id/confirm/',
    getParentRoute: () => OrderLayoutCompanyLocation_idUser_idRouteRoute,
  } as any)
const OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute =
  OrderLayoutCompanyLocation_idUser_idService_idDateIndexRouteImport.update({
    id: '/$service_id/date/',
    path: '/$service_id/date/',
    getParentRoute: () => OrderLayoutCompanyLocation_idUser_idRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof OrderLayoutIndexRoute
  '/$notFound': typeof OrderLayoutNotFoundRoute
  '/success/': typeof OrderLayoutSuccessIndexRoute
  '/$company/$location_id/$user_id': typeof OrderLayoutCompanyLocation_idUser_idRouteRouteWithChildren
  '/$company/$location_id/$user_id/': typeof OrderLayoutCompanyLocation_idUser_idIndexRoute
  '/$company/$location_id/$user_id/$service_id/confirm/': typeof OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute
  '/$company/$location_id/$user_id/$service_id/date/': typeof OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof OrderLayoutIndexRoute
  '/$notFound': typeof OrderLayoutNotFoundRoute
  '/success': typeof OrderLayoutSuccessIndexRoute
  '/$company/$location_id/$user_id': typeof OrderLayoutCompanyLocation_idUser_idIndexRoute
  '/$company/$location_id/$user_id/$service_id/confirm': typeof OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute
  '/$company/$location_id/$user_id/$service_id/date': typeof OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_order': typeof OrderRouteRouteWithChildren
  '/_order/_layout': typeof OrderLayoutRouteRouteWithChildren
  '/_order/_layout/$notFound': typeof OrderLayoutNotFoundRoute
  '/_order/_layout/': typeof OrderLayoutIndexRoute
  '/_order/_layout/success/': typeof OrderLayoutSuccessIndexRoute
  '/_order/_layout/$company/$location_id/$user_id': typeof OrderLayoutCompanyLocation_idUser_idRouteRouteWithChildren
  '/_order/_layout/$company/$location_id/$user_id/': typeof OrderLayoutCompanyLocation_idUser_idIndexRoute
  '/_order/_layout/$company/$location_id/$user_id/$service_id/confirm/': typeof OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute
  '/_order/_layout/$company/$location_id/$user_id/$service_id/date/': typeof OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$notFound'
    | '/success/'
    | '/$company/$location_id/$user_id'
    | '/$company/$location_id/$user_id/'
    | '/$company/$location_id/$user_id/$service_id/confirm/'
    | '/$company/$location_id/$user_id/$service_id/date/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$notFound'
    | '/success'
    | '/$company/$location_id/$user_id'
    | '/$company/$location_id/$user_id/$service_id/confirm'
    | '/$company/$location_id/$user_id/$service_id/date'
  id:
    | '__root__'
    | '/_order'
    | '/_order/_layout'
    | '/_order/_layout/$notFound'
    | '/_order/_layout/'
    | '/_order/_layout/success/'
    | '/_order/_layout/$company/$location_id/$user_id'
    | '/_order/_layout/$company/$location_id/$user_id/'
    | '/_order/_layout/$company/$location_id/$user_id/$service_id/confirm/'
    | '/_order/_layout/$company/$location_id/$user_id/$service_id/date/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrderRouteRoute: typeof OrderRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_order': {
      id: '/_order'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_order/_layout': {
      id: '/_order/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrderLayoutRouteRouteImport
      parentRoute: typeof OrderRouteRoute
    }
    '/_order/_layout/': {
      id: '/_order/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OrderLayoutIndexRouteImport
      parentRoute: typeof OrderLayoutRouteRoute
    }
    '/_order/_layout/$notFound': {
      id: '/_order/_layout/$notFound'
      path: '/$notFound'
      fullPath: '/$notFound'
      preLoaderRoute: typeof OrderLayoutNotFoundRouteImport
      parentRoute: typeof OrderLayoutRouteRoute
    }
    '/_order/_layout/success/': {
      id: '/_order/_layout/success/'
      path: '/success'
      fullPath: '/success/'
      preLoaderRoute: typeof OrderLayoutSuccessIndexRouteImport
      parentRoute: typeof OrderLayoutRouteRoute
    }
    '/_order/_layout/$company/$location_id/$user_id': {
      id: '/_order/_layout/$company/$location_id/$user_id'
      path: '/$company/$location_id/$user_id'
      fullPath: '/$company/$location_id/$user_id'
      preLoaderRoute: typeof OrderLayoutCompanyLocation_idUser_idRouteRouteImport
      parentRoute: typeof OrderLayoutRouteRoute
    }
    '/_order/_layout/$company/$location_id/$user_id/': {
      id: '/_order/_layout/$company/$location_id/$user_id/'
      path: '/'
      fullPath: '/$company/$location_id/$user_id/'
      preLoaderRoute: typeof OrderLayoutCompanyLocation_idUser_idIndexRouteImport
      parentRoute: typeof OrderLayoutCompanyLocation_idUser_idRouteRoute
    }
    '/_order/_layout/$company/$location_id/$user_id/$service_id/confirm/': {
      id: '/_order/_layout/$company/$location_id/$user_id/$service_id/confirm/'
      path: '/$service_id/confirm'
      fullPath: '/$company/$location_id/$user_id/$service_id/confirm/'
      preLoaderRoute: typeof OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRouteImport
      parentRoute: typeof OrderLayoutCompanyLocation_idUser_idRouteRoute
    }
    '/_order/_layout/$company/$location_id/$user_id/$service_id/date/': {
      id: '/_order/_layout/$company/$location_id/$user_id/$service_id/date/'
      path: '/$service_id/date'
      fullPath: '/$company/$location_id/$user_id/$service_id/date/'
      preLoaderRoute: typeof OrderLayoutCompanyLocation_idUser_idService_idDateIndexRouteImport
      parentRoute: typeof OrderLayoutCompanyLocation_idUser_idRouteRoute
    }
  }
}

interface OrderLayoutCompanyLocation_idUser_idRouteRouteChildren {
  OrderLayoutCompanyLocation_idUser_idIndexRoute: typeof OrderLayoutCompanyLocation_idUser_idIndexRoute
  OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute: typeof OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute
  OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute: typeof OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute
}

const OrderLayoutCompanyLocation_idUser_idRouteRouteChildren: OrderLayoutCompanyLocation_idUser_idRouteRouteChildren =
  {
    OrderLayoutCompanyLocation_idUser_idIndexRoute:
      OrderLayoutCompanyLocation_idUser_idIndexRoute,
    OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute:
      OrderLayoutCompanyLocation_idUser_idService_idConfirmIndexRoute,
    OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute:
      OrderLayoutCompanyLocation_idUser_idService_idDateIndexRoute,
  }

const OrderLayoutCompanyLocation_idUser_idRouteRouteWithChildren =
  OrderLayoutCompanyLocation_idUser_idRouteRoute._addFileChildren(
    OrderLayoutCompanyLocation_idUser_idRouteRouteChildren,
  )

interface OrderLayoutRouteRouteChildren {
  OrderLayoutNotFoundRoute: typeof OrderLayoutNotFoundRoute
  OrderLayoutIndexRoute: typeof OrderLayoutIndexRoute
  OrderLayoutSuccessIndexRoute: typeof OrderLayoutSuccessIndexRoute
  OrderLayoutCompanyLocation_idUser_idRouteRoute: typeof OrderLayoutCompanyLocation_idUser_idRouteRouteWithChildren
}

const OrderLayoutRouteRouteChildren: OrderLayoutRouteRouteChildren = {
  OrderLayoutNotFoundRoute: OrderLayoutNotFoundRoute,
  OrderLayoutIndexRoute: OrderLayoutIndexRoute,
  OrderLayoutSuccessIndexRoute: OrderLayoutSuccessIndexRoute,
  OrderLayoutCompanyLocation_idUser_idRouteRoute:
    OrderLayoutCompanyLocation_idUser_idRouteRouteWithChildren,
}

const OrderLayoutRouteRouteWithChildren =
  OrderLayoutRouteRoute._addFileChildren(OrderLayoutRouteRouteChildren)

interface OrderRouteRouteChildren {
  OrderLayoutRouteRoute: typeof OrderLayoutRouteRouteWithChildren
}

const OrderRouteRouteChildren: OrderRouteRouteChildren = {
  OrderLayoutRouteRoute: OrderLayoutRouteRouteWithChildren,
}

const OrderRouteRouteWithChildren = OrderRouteRoute._addFileChildren(
  OrderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OrderRouteRoute: OrderRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
